{% set name = "nose2" %}
{% set version = "0.8.0" %}
{% set sha256 = "9052f2b46807b63d9bdf68e0768da1f8386368889b50043fd5d0889c470258f3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - nose2 = nose2:discover
    - nose2-3.6 = nose2:discover

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - six >=1.7
    - coverage >=4.4.1

test:
  imports:
    - nose2
    - nose2.plugins
    - nose2.plugins.loader
    - nose2.tests
    - nose2.tests.functional
    - nose2.tests.unit
    - nose2.tools
  commands:
    - nose2 --help
    - nose2-3.6 --help

about:
  home: https://github.com/nose-devs/nose2
  summary: 'nose2 is the next generation of nicer testing for Python'
  license: BSD
  license_family: BSD
  license_file: license.txt

extra:
  recipe-maintainers:
    - npavlovikj
