{% set name = "nose2" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57c68ad676ef4b88b50694937eb52f4943aa1ca261074b4909b6e163046b46f0

build:
  skip: true  # [py>=311]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - nose2 = nose2:discover
    - nose2-{{ python }} = nose2:discover

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - nose2
    - nose2.plugins
    - nose2.plugins.loader
    - nose2.tests
    - nose2.tests.functional
    - nose2.tests.unit
    - nose2.tools
  requires:
    - pip
  commands:
    - pip check
    - nose2 --help
    - nose2-{{ python }} --help
about:
  home: https://github.com/nose-devs/nose2
  description: The successor to nose, based on unittest2
  summary: nose2 is the next generation of nicer testing for Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/nose-devs/nose2
  doc_url: https://docs.nose2.io/en/latest/

extra:
  recipe-maintainers:
    - npavlovikj
