travis:
  secure:
    BINSTAR_TOKEN: jgIBy4CO9oDBJZrcdk07SjqLnZgBmqBY1DRbXiQ8gdbWSBS+nlkBRcwgtvs9PlzKIK6GP8mFN9Yd9aaj83aeHkONKfNEzhn8NeqDFNcOW25zBG6+3RdL6ebbW2KR103AFJuRkScrF5LlpFtioaPRf6OVfSdS0UJ+mVEji/FQR2lSbPhah0q7HzWrEvXaI4ejzuNowSgl+QYfhb3yAiFzp+nqPOyDc+LIFXtiu6DsTK2936uwxfrC2zf50P+IdFeW2diWqMx/pSy7xL+gXiTI75S8iVnzjVn7P4HzWpYhqHG7DJCkH789a5jP6oho/c9wz39SBL7AyNrkCHdkNXxx+5PJT5SEbk6HITqR+NjHp2B+Hd2H9MzijDchnNcB4ylZa6f080HneM3KaeaFHGeyPJHL8jzjIg259G5nQrz/Gjfu4oVVQU/rPjWs8q5whnJXIIauXavtb4qbZA6M2CWSzAycRuVarAg0IL5avlGtjeHJUfka+BignLWqkZMTwILPJzzdEltbVffiPya2cqtNgL0TFxrjBJyFMKTzm8E/96Q/Bx1KqinTX2o2AGCy5khV2QSph2iXLahvckpWhZzBNVHfoP9pnqs1JJRFBdYbZKpDt4kFuxplLRWWTIMH7cTNp5sQhGIklZJTeFlPh/I/c2wyZ5McgQwXOWzc5DM7B68=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
