travis:
  secure:
    BINSTAR_TOKEN: KIbis/YoGpjZF1roXvBNzsajZau7yp4zhbGmILmyq2X99x9xk09nODm7wDqWuUzufi5hds5MaxN8CPZ5/Pkw6rxVwr3iJPnCA4Cjwdkp8I5UuAxztnXbel5lTdiUrXdhm2vYgwo8+H5zG+HAOtMavIXsDNGnqD3q8ibDLO1BEBCErrvebUxmkol/u+fDXH/7Q0fKGvYxSb+LK5sQmmgryLfKyqCNL97vi/Eb2TBEfBG9Eaa6XCFkYFxzXVLsLF1xvLl30qSQe9GKoEPsXFyWwRbcUKaddFmPnxLcLWHbvzDlF9ZhH7Oi3iahichXgmzz/hbby9O6CAexFJzTihP14JvltkRciaR5XvMAP8dOkqNqQstf6HrNAKp/hTbi/8XcHh4m6rxSKdw0VJ3aRW3yAXvw6cGLhzZZkZyyfoPMKLmG/hJCPAzJjsQxKKc0O6+DkRgJvmnTgkuLsm57+rsbxlyPbIgj1tfmOSLZ0alXDdQMTSvBs+wknHg7Z3IS/6LYy7oCAKw6crKPawtj/MNuLvlyv0tb+LvF3YYryRk2eIpql/AKGtZ2z13F/Wzi+3nyVMkHIEDnOM7+nqQtBiAvmrGjV4ibXMwrumJxddiSRFhXdbGcfo0lda70XHOJ3gKyau6ykyc3X13dorghwl5DMCFBr+1Y5BMOVO8cbN5tp90=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
