travis:
  secure:
    BINSTAR_TOKEN: kkcmWHyuGsf5Dn7+hPUmS+XHD9IdLNYAFrvMZhOYy3Tc/lO2vB2rZFyjtbSCu+ME57hDQ0WHJoAOTyd/rRxSof2nZdyYNqUVVprZ64Jl0WLImjXwH5rdsnKOpIy+68ZTXs+dO05V81BgROXCJjsBwOprUDDIl9fPhKV//8TrmTaPSd6v9wIdDq5EzWWY3j63zXz0Om5R8P4aWlRnk6AmfUbEe87G23BFy2c3Fb6Ij9ykWFoy6uEuvecTk+xrYUHMqu8vcOLgS4zwMEHUTNBNpR4UExXDdITVV3jAP+IJ3EXpbKyC0bqkU9Anld2i8516FnUEsYC1zZ0WJdZMYwjM254VTI04mvqycPjJWmHOlXXMp328bR+As0GS83tAoI8s2oRiyjg4lplSy95AtguFImeOr+rkzF0FBlkcKmtNmQv8kSk5nDrgKKVxxzOBcWunKrbJlZF3uW6PASzvUw2/MFM5vQeM1iqPgBPCTKP4D3nhwv3Efvi9YNILRGLX10gcHVFDem8F/wYDiZbgO5twKeHj8yIbenmE9ebQhplBDqvVgHdrKodmAvaz9iYeWPFPHW8kDwF1OUT+hGE+Y9W1msDYSNp/WN0FWDxNZXAGD7Rg7zeRpP8LdiM7ztkkoLmZyY/rC3ezeSDJhPS+nH7hojk6tx6dFl9I4Dx16AAhzU4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
